### Assignment 5

In [15]:
import random
import numpy as np
import matplotlib.pyplot as plt

In [131]:
attack_dices = [np.random.randint(1, 6, 3) for _ in range(3)]
for attack_dice in attack_dices:
  print(attack_dice)

  

[3 3 3]
[3 5 5]
[3 5 5]


In [137]:
defense_dices = [np.random.randint(1, 6, 2) for _ in range(3)]
for defense_dice in defense_dices:
  print(defense_dice)

[3 4]
[1 5]
[3 1]


In [143]:
for attack_dice in range(3):

   if np.max((attack_dice)) > np.max((defense_dice)):
      print(1)
   elif: 
      print(0)
    


SyntaxError: invalid syntax (2069560599.py, line 5)